### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [anselmh/AMA#14]

**Comment by anselmh** [comment]
Kind of. I don’t do much public coaching or mentoring stuff (like online courses / videos). I do write blog posts to give other people the chance to learn from my mistakes or explorations. I did video courses (paid) a few years ago but it wasn’t my type of teaching.
I irregularly give public on-site workshops and I regularly give advice or teach other developers in person.

Regarding the "mentoring" I think I don’t do this as I don’t do it regular and not for one person over a certain timeframe.
