### ISSUE TITLE
Have you ever tried Polymer?

### ISSUE THREAD

**Issue by tenhobi** [anselmh/AMA#15]

**Comment by anselmh** [comment]
I tried it once but never on any real project but just to evaluate it. In my case it wasn’t worth the overhead that it brings with it and so I never used it again. I also have the strong feeling that it’s evolved towards more of a UI framework than its original purpose to polyfill web components.

**Comment by tenhobi** [comment]
Well, you have Polymer which do all the stuff with polyfilling web components and you also have elements from catalog, which are more like separate project - something like Bootstrap for CSS.

I like the idea of Polymer and I create my own elements for our app http://nottelo.com. :smirk_cat:
