### ISSUE TITLE
How do you setup TOR and a VPN on your computer?

### ISSUE THREAD

**Issue by MarcoHengstenberg** [anselmh/AMA#17]
This might be a pretty straight forward question where the answer could be any link to any tutorial explaining the hows and whys and all but I want to add one thing:

Is your browsing experience terrible with those enabled and if not why? :laughing: 

(cuz whenever I do, I get the worst and slowest experience of all time – and I've been on the web with a 28.8k modem back in the days)

**Comment by anselmh** [comment]
**For Tor** I use the [Torbrowser](https://www.torproject.org/projects/torbrowser.html.en) with the default settings. It mostly works fine but if it’s too slow you can still try to get a new route.

**For VPN** there are a lot of privacy services but I use only two options here: 
1) My own VPN which is running on my router (mostly not for privacy reasons, won’t help for VDS)
2) [Disconnect Premium](https://disconnect.me/) service. Block privacy leaking scripts and provides a secure, fast VPN for Desktop and iPhone (but it seems Apple just removed their app from the AppStore, glad I still have it)

**Comment by anselmh** [comment]
Got the hint that https://proxy.sh/ is also a got bet for a VPN.

**Comment by MarcoHengstenberg** [comment]
Thanks for the answers.

Related question: what do you think of the new EpicBrowser? https://www.epicbrowser.com/
Built on Chrome (currently 40) with built-in Tor Proxy and autoblocking all tracking scripts and so on and so forth...
I gave it a try and while the blocking and privacy is truely amazing, the speed make the whole experience not so much worthwhile. =(

**Comment by anselmh** [comment]
Oh, I don’t know it. Honestly, I’d only use the official browser but it’s up to you and if it’s open source it might be totally fine to use it.
