### ISSUE TITLE
what's your favorite/most-effective learning method?

### ISSUE THREAD

**Issue by ahmadnassri** [anselmh/AMA#18]

**Comment by anselmh** [comment]
Thanks for this interesting question. Actually I’m pretty bad with theoretical learning. That’s why I always prefer practical examples, and trying out things until they work. With a couple of examples being done I usually research particular facts in books or references. For things I practiced a lot and am interested a lot (like CSS, HTML, JS), I sometimes try to understand the specification which gives you lots of small details on why things work like they do.

For sources to learn I prefer:
- short blog posts
- short wiki articles
- tutorials (step by step guides)
- short book chapters (I prefer physical books)
- try on my own

**Comment by anselmh** [comment]
Related I found this article summarizes a few good techniques: https://the-pastry-box-project.net/erin-mckean/2015-october-24
