### ISSUE TITLE
What would you make if you had infinite time and zero distractions?

### ISSUE THREAD

**Issue by arthurvr** [anselmh/AMA#2]

**Comment by anselmh** [comment]
Great question, yet hard to answer. At the moment I think I would do more open source work again, work much more on side-projects (that now are only in my head). It would also enable me to spend more time in my beloved mountains (biking, hiking, climbing) and probably spend more time working together with real people and communities.

Thinking about this a little bit more I realize asking this question is a great way to reflect on one’s current work and life situation. Maybe it can help to improve and **I’d really like to hear this from my readers, too, so I leave this open for a bit**.
