### ISSUE TITLE
Building a custom VW Camping Car DIY style

### ISSUE THREAD

**Issue by anselmh** [anselmh/AMA#20]
This is the Q&A thread for the blog article “[Building a custom VW Camping Car DIY style](https://helloanselm.com/2017/backstory-vw-camper-van/)”.

Ask me anything.

**Comment by nilswindisch** [comment]
Great project :)

Did you get a as-is set with all the parts for the battery/outlet/installation? If so which one and can you recommend it?

oh, and why did you decide against the a battery in the passenger seat console?

**Comment by anselmh** [comment]
No, it's completely custom set of electronic parts. I have an external power supply for 230V supply and a Gel battery. I heard some things about the prebuilt sets but honestly I now don't think one should do that without specific knowledge about car electricity. It's not very easy to connect the second battery with the main one correctly.

The battery isn't suitable for under the seat (too big) which is the main reason not putting it under the driver's seat. The passenger seat isn't suitable as I have the double seat there and need the space of the trunk inside the seat for various other things.
