### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by petrpscolka** [anselmh/AMA#21]
I am looking for some vacation destination.
Please, can you tell me, where did you catch your cover photo?
Thank You, Petr
https://helloanselm.com/content/4-photography/photography-2016-12.jpg

**Comment by anselmh** [comment]
@petrpscolka Thanks for asking, this is taken in the mountains in Norway. I think somewhere in the area near a town called Odda. A georgeous place though it was very chill and windy there.

**Comment by petrpscolka** [comment]
Wau, Thank you
