### ISSUE TITLE
What's your favorite part about web development?

### ISSUE THREAD

**Issue by sindresorhus** [anselmh/AMA#4]

**Comment by anselmh** [comment]
Hard question. I really like the approach of web development in comparison to higher language development: It’s nice to have no need for a compiling step, it’s nice to have fallbacks, failovers (CSS), graceful degradation, progressive enhancement and live debugging. I also like the challenges of cross-browser inconsistencies (though they can sometimes be a PITA), multiple device sizes, different requirements for every project. And I like our community which is a great thing. Keep in mind that other industries don’t have such an open, active community which is able to help in a few minutes and shares approaches in the open. Just apply this to a banker or business manager. I hardly can imagine.
