### ISSUE TITLE
What do you like and dislike about being a freelancer?

### ISSUE THREAD

**Issue by sindresorhus** [anselmh/AMA#8]

**Comment by anselmh** [comment]
Like:
- I can manage time mostly on my own (like taking a day off during the week)
- I can choose which clients I want to work for and which not
- Freedom of work
- No focus on one project all the time (for me it gets a bit boring to work on the same client project over a year)

Dislike:
- It’s hard to manage time all on your own, stay focused
- It’s even harder to take breaks and preserve some private life (known as good work-life balance)
- No steady income, always some kind of “fear” what’s happening next
